"""add_cancellation_reason_to_client_files

Revision ID: bbc216661bee
Revises: 68f35cf53e83
Create Date: 2026-04-28 11:24:23.243071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc216661bee'
down_revision: Union[str, Sequence[str], None] = '68f35cf53e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_files', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_files', 'cancellation_reason')
    # ### end Alembic commands ###
