"""add_rejection_reason_to_client_files

Revision ID: beaab374f5a4
Revises: bbc216661bee
Create Date: 2026-04-28 11:34:34.527322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beaab374f5a4'
down_revision: Union[str, Sequence[str], None] = 'bbc216661bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_files', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_files', 'rejection_reason')
    # ### end Alembic commands ###
